# Generated by Django 5.2.8 on 2026-01-17 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basket', '0001_initial'),
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='baskets',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='basketitem',
            name='basket',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='baskets',
                to='basket.basket',
            ),
        ),
        migrations.AddField(
            model_name='basketitem',
            name='device',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='devices_in_basket',
                to='devices.device',
            ),
        ),
        migrations.AddField(
            model_name='basket',
            name='devices',
            field=models.ManyToManyField(
                related_name='baskets',
                through='basket.BasketItem',
                to='devices.device',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='basketitem',
            unique_together={('basket', 'device')},
        ),
    ]
