# Generated by Django 5.2.8 on 2026-01-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_initial'),
        (
            'devices',
            '0003_alter_rating_options_alter_rating_unique_together_and_more',
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='basketitem',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='basketitem',
            constraint=models.UniqueConstraint(
                fields=('basket', 'device'), name='unique_basket_device'
            ),
        ),
    ]
