# Generated by Django 5.2.8 on 2026-02-20 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_alter_basketitem_unique_together_and_more'),
        (
            'devices',
            '0003_alter_rating_options_alter_rating_unique_together_and_more',
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={
                'default_related_name': 'baskets',
                'ordering': ['-created_at'],
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.AlterField(
            model_name='basket',
            name='devices',
            field=models.ManyToManyField(
                through='basket.BasketItem', to='devices.device'
            ),
        ),
        migrations.AlterField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='basket',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='items',
                to='basket.basket',
            ),
        ),
    ]
