.PHONY: install ci-install dev build start lint generate-api test test-watch check ci-check

install:
	@npm install

ci-install:
	@npm ci

dev:
	@npm run dev

build:
	@npm run build

start:
	@npm run start

lint:
	@npm run lint

generate-api:
	@npm run generate-api

test:
	@npm run test

test-watch:
	@npm run test:watch

check:
	@npm run check

ci-check:
	@npm run ci:check