/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/auth/login/code/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Request Login Code View */
    post: operations["api_v1_auth_handlers_request_login_code_view"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/login/confirm/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Confirm View */
    post: operations["api_v1_auth_handlers_confirm_view"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/invite-confirm/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Invite Confirm View */
    post: operations["api_v1_auth_handlers_invite_confirm_view"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/logout/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout View */
    post: operations["api_v1_auth_handlers_logout_view"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/user/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Invite User View */
    post: operations["api_v1_admin_handlers_invite_user_view"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/users/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Users List View */
    get: operations["api_v1_admin_handlers_get_users_list_view"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/profile/me/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get User View */
    get: operations["api_v1_profile_handlers_get_user_view"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update User View */
    patch: operations["api_v1_profile_handlers_update_user_view"];
    trace?: never;
  };
  "/api/v1/profile/problems/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get My Problems List View */
    get: operations["api_v1_problems_handlers_profile_get_my_problems_list_view"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/profile/problems/{problem_id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get My Problem Detail View */
    get: operations["api_v1_problems_handlers_profile_get_my_problem_detail_view"];
    put?: never;
    post?: never;
    /** Delete My Problem View */
    delete: operations["api_v1_problems_handlers_profile_delete_my_problem_view"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/profile/subjects/{subject_slug}/problems/{problem_id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update My Problem View */
    patch: operations["api_v1_problems_handlers_profile_update_my_problem_view"];
    trace?: never;
  };
  "/api/v1/profile/subjects/{subject_slug}/problems/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Problem View */
    post: operations["api_v1_problems_handlers_profile_create_problem_view"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/profile/problems/{problem_id}/solutions/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Solution View */
    post: operations["api_v1_solutions_handlers_create_solution_view"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/profile/problems/{problem_id}/solutions/{solution_id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Solution View */
    patch: operations["api_v1_solutions_handlers_update_solution_view"];
    trace?: never;
  };
  "/api/v1/profile/problems/{problem_id}/main-solution/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Set Main Solution View */
    patch: operations["api_v1_solutions_handlers_set_main_solution_view"];
    trace?: never;
  };
  "/api/v1/subjects/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Subjects View */
    get: operations["api_v1_subjects_handlers_get_subjects_view"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/subjects/{subject_slug}/problems/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Public Problems List View */
    get: operations["api_v1_problems_handlers_subject_get_public_problems_list_view"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/subjects/{subject_slug}/problems/filters/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Problems Filters View */
    get: operations["api_v1_problems_handlers_subject_get_problems_filters_view"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/problems/recent/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Recent Problems List View */
    get: operations["api_v1_problems_handlers_public_get_recent_problems_list_view"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/problems/{problem_id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Public Problem Detail View */
    get: operations["api_v1_problems_handlers_public_get_public_problem_detail_view"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ApiError */
    ApiError: {
      /** Message */
      message: string;
      /** Extra */
      extra?: {
        [key: string]: unknown;
      } | null;
    };
    /** ApiResponse[AuthOutSchema] */
    ApiResponse_AuthOutSchema_: {
      data?: components["schemas"]["AuthOutSchema"] | null;
      /** Meta */
      meta?: {
        [key: string]: unknown;
      };
      /** Errors */
      errors?: components["schemas"]["ApiError"][];
    };
    /** AuthOutSchema */
    AuthOutSchema: {
      /** Message */
      message: string;
    };
    /** AuthInputSchema */
    AuthInputSchema: {
      /** Email */
      email: string;
    };
    /** ApiResponse[AuthUserOutSchema] */
    ApiResponse_AuthUserOutSchema_: {
      data?: components["schemas"]["AuthUserOutSchema"] | null;
      /** Meta */
      meta?: {
        [key: string]: unknown;
      };
      /** Errors */
      errors?: components["schemas"]["ApiError"][];
    };
    /** AuthUserOutSchema */
    AuthUserOutSchema: {
      user: components["schemas"]["UserOutSchema"];
    };
    /** UserOutSchema */
    UserOutSchema: {
      /** Id */
      id: number;
      /** First Name */
      first_name?: string | null;
      /** Last Name */
      last_name?: string | null;
      /** Full Name */
      full_name?: string | null;
      /** Email */
      email: string;
      /** Username */
      username: string;
      /** Is Active */
      is_active: boolean;
      /** Is Staff */
      is_staff: boolean;
      /**
       * Date Joined
       * Format: date-time
       */
      date_joined: string;
    };
    /** ConfirmEmailInputSchema */
    ConfirmEmailInputSchema: {
      /** Email */
      email: string;
      /** Code */
      code: string;
    };
    /** InviteTokenConfirmIn */
    InviteTokenConfirmIn: {
      /** Token */
      token: string;
    };
    /** ApiResponse[MessageSchema] */
    ApiResponse_MessageSchema_: {
      data?: components["schemas"]["MessageSchema"] | null;
      /** Meta */
      meta?: {
        [key: string]: unknown;
      };
      /** Errors */
      errors?: components["schemas"]["ApiError"][];
    };
    /** MessageSchema */
    MessageSchema: {
      /** Message */
      message: string;
    };
    /** UserInputSchema */
    UserInputSchema: {
      /** Email */
      email: string;
    };
    /** PaginationIn */
    PaginationIn: {
      /**
       * Offset
       * @default 0
       */
      offset: number;
      /**
       * Limit
       * @default 10
       */
      limit: number;
    };
    /** UserFiltersIn */
    UserFiltersIn: {
      /** Created From */
      created_from?: string | null;
      /** Created To */
      created_to?: string | null;
      /** Search */
      search?: string | null;
      /** Is Active */
      is_active?: boolean | null;
    };
    /** ApiResponse[ListPaginationResponse[UserOutSchema]] */
    ApiResponse_ListPaginationResponse_UserOutSchema__: {
      data?:
        | components["schemas"]["ListPaginationResponse_UserOutSchema_"]
        | null;
      /** Meta */
      meta?: {
        [key: string]: unknown;
      };
      /** Errors */
      errors?: components["schemas"]["ApiError"][];
    };
    /** ListPaginationResponse[UserOutSchema] */
    ListPaginationResponse_UserOutSchema_: {
      /** Items */
      items: components["schemas"]["UserOutSchema"][];
      pagination: components["schemas"]["PaginationOut"];
    };
    /** PaginationOut */
    PaginationOut: {
      /** Offset */
      offset: number;
      /** Limit */
      limit: number;
      /** Total */
      total: number;
    };
    /** ApiResponse[UserOutSchema] */
    ApiResponse_UserOutSchema_: {
      data?: components["schemas"]["UserOutSchema"] | null;
      /** Meta */
      meta?: {
        [key: string]: unknown;
      };
      /** Errors */
      errors?: components["schemas"]["ApiError"][];
    };
    /** UserUpdateSchema */
    UserUpdateSchema: {
      /** Username */
      username?: string | null;
      /** First Name */
      first_name?: string | null;
      /** Last Name */
      last_name?: string | null;
    };
    /**
     * Difficulty
     * @enum {string}
     */
    Difficulty: "easy" | "medium" | "hard";
    /** MyProblemsFilterInSchema */
    MyProblemsFilterInSchema: {
      /** Created From */
      created_from?: string | null;
      /** Created To */
      created_to?: string | null;
      /** Search */
      search?: string | null;
      /**
       * Section Ids
       * @default []
       */
      section_ids: number[];
      /**
       * Topic Ids
       * @default []
       */
      topic_ids: number[];
      /**
       * Tag Ids
       * @default []
       */
      tag_ids: number[];
      difficulty?: components["schemas"]["Difficulty"] | null;
      status?: components["schemas"]["PublicationStatus"] | null;
      /** Subject Slug */
      subject_slug?: string | null;
    };
    /**
     * PublicationStatus
     * @enum {string}
     */
    PublicationStatus: "draft" | "published";
    /** ApiResponse[ListPaginationResponse[ProblemOutSchema]] */
    ApiResponse_ListPaginationResponse_ProblemOutSchema__: {
      data?:
        | components["schemas"]["ListPaginationResponse_ProblemOutSchema_"]
        | null;
      /** Meta */
      meta?: {
        [key: string]: unknown;
      };
      /** Errors */
      errors?: components["schemas"]["ApiError"][];
    };
    /** DifficultyOutSchema */
    DifficultyOutSchema: {
      /** Value */
      value: string;
      /** Label */
      label: string;
    };
    /** ListPaginationResponse[ProblemOutSchema] */
    ListPaginationResponse_ProblemOutSchema_: {
      /** Items */
      items: components["schemas"]["ProblemOutSchema"][];
      pagination: components["schemas"]["PaginationOut"];
    };
    /** ProblemOutSchema */
    ProblemOutSchema: {
      /** Id */
      id: number;
      /** Title */
      title: string;
      /** Question */
      question: string;
      /** Source */
      source: string;
      difficulty: components["schemas"]["DifficultyOutSchema"];
      status: components["schemas"]["StatusOutSchema"];
      subject?: components["schemas"]["SubjectOutSchema"] | null;
      section: components["schemas"]["SectionOutSchema"];
      topic: components["schemas"]["TopicOutSchema"];
      /** Tags */
      tags: components["schemas"]["TagOutSchema"][];
      author?: components["schemas"]["UserShortOutSchema"] | null;
      /** Solutions */
      solutions: components["schemas"]["SolutionOutSchema"][];
      permissions: components["schemas"]["ProblemPermissionsOutSchema"];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** ProblemPermissionsOutSchema */
    ProblemPermissionsOutSchema: {
      /** Can Edit */
      can_edit: boolean;
      /** Can Create Solution */
      can_create_solution: boolean;
    };
    /** SectionOutSchema */
    SectionOutSchema: {
      /** Id */
      id: number;
      /** Name */
      name: string;
      /** Subject Id */
      subject_id: number;
    };
    /** SolutionOutSchema */
    SolutionOutSchema: {
      /** Id */
      id: number;
      /** Name */
      name: string;
      /** Content */
      content: string;
      /** Is Main */
      is_main: boolean;
      author: components["schemas"]["UserShortOutSchema"] | null;
      /** Is Published */
      is_published: boolean;
      permissions: components["schemas"]["SolutionPermissionsOutSchema"];
    };
    /** SolutionPermissionsOutSchema */
    SolutionPermissionsOutSchema: {
      /** Can Edit */
      can_edit: boolean;
    };
    /** StatusOutSchema */
    StatusOutSchema: {
      /** Value */
      value: string;
      /** Label */
      label: string;
    };
    /** SubjectOutSchema */
    SubjectOutSchema: {
      /** Id */
      id: number;
      /** Name */
      name: string;
      /** Slug */
      slug: string;
    };
    /** TagOutSchema */
    TagOutSchema: {
      /** Id */
      id: number;
      /** Name */
      name: string;
    };
    /** TopicOutSchema */
    TopicOutSchema: {
      /** Id */
      id: number;
      /** Name */
      name: string;
      /** Section Id */
      section_id: number;
    };
    /** UserShortOutSchema */
    UserShortOutSchema: {
      /** Id */
      id: number;
      /** Username */
      username: string;
      /** First Name */
      first_name?: string | null;
      /** Last Name */
      last_name?: string | null;
      /** Full Name */
      full_name?: string | null;
    };
    /** ApiResponse[ProblemOutSchema] */
    ApiResponse_ProblemOutSchema_: {
      data?: components["schemas"]["ProblemOutSchema"] | null;
      /** Meta */
      meta?: {
        [key: string]: unknown;
      };
      /** Errors */
      errors?: components["schemas"]["ApiError"][];
    };
    /** ApiResponse[ProblemMutationOutSchema] */
    ApiResponse_ProblemMutationOutSchema_: {
      data?: components["schemas"]["ProblemMutationOutSchema"] | null;
      /** Meta */
      meta?: {
        [key: string]: unknown;
      };
      /** Errors */
      errors?: components["schemas"]["ApiError"][];
    };
    /** ProblemMutationOutSchema */
    ProblemMutationOutSchema: {
      /** Id */
      id: number;
      /** Subject Slug */
      subject_slug: string;
      /** Detail Url */
      detail_url: string;
    };
    /** ProblemUpdateInSchema */
    ProblemUpdateInSchema: {
      /** Title */
      title?: string | null;
      /** Question */
      question?: string | null;
      difficulty?: components["schemas"]["Difficulty"] | null;
      /** Source */
      source?: string | null;
      /** Topic Id */
      topic_id?: number | null;
      /** Tag Ids */
      tag_ids?: number[] | null;
      status?: components["schemas"]["PublicationStatus"] | null;
    };
    /** ProblemCreateInSchema */
    ProblemCreateInSchema: {
      /** Title */
      title: string;
      /** Question */
      question: string;
      difficulty: components["schemas"]["Difficulty"];
      /** Source */
      source: string;
      /** Topic Id */
      topic_id: number;
      /** Tag Ids */
      tag_ids: number[];
      /** @default draft */
      status: components["schemas"]["PublicationStatus"];
    };
    /** ApiResponse[SolutionMutationOutSchema] */
    ApiResponse_SolutionMutationOutSchema_: {
      data?: components["schemas"]["SolutionMutationOutSchema"] | null;
      /** Meta */
      meta?: {
        [key: string]: unknown;
      };
      /** Errors */
      errors?: components["schemas"]["ApiError"][];
    };
    /** SolutionMutationOutSchema */
    SolutionMutationOutSchema: {
      /** Problem Id */
      problem_id: number;
      /** Solution Id */
      solution_id: number;
      /** Detail Url */
      detail_url: string;
    };
    /** SolutionCreateInSchema */
    SolutionCreateInSchema: {
      /** Name */
      name: string;
      /** Content */
      content: string;
      /** Is Published */
      is_published: boolean;
    };
    /** SolutionUpdateInSchema */
    SolutionUpdateInSchema: {
      /** Name */
      name?: string | null;
      /** Content */
      content?: string | null;
      /** Is Published */
      is_published?: boolean | null;
    };
    /** SetMainSolutionInSchema */
    SetMainSolutionInSchema: {
      /** Solution Id */
      solution_id: number;
    };
    /** ApiResponse[list[SubjectOutSchema]] */
    ApiResponse_list_SubjectOutSchema__: {
      /** Data */
      data?: components["schemas"]["SubjectOutSchema"][] | null;
      /** Meta */
      meta?: {
        [key: string]: unknown;
      };
      /** Errors */
      errors?: components["schemas"]["ApiError"][];
    };
    /** PublicProblemsFilterInSchema */
    PublicProblemsFilterInSchema: {
      /** Created From */
      created_from?: string | null;
      /** Created To */
      created_to?: string | null;
      /** Search */
      search?: string | null;
      /**
       * Section Ids
       * @default []
       */
      section_ids: number[];
      /**
       * Topic Ids
       * @default []
       */
      topic_ids: number[];
      /**
       * Tag Ids
       * @default []
       */
      tag_ids: number[];
      difficulty?: components["schemas"]["Difficulty"] | null;
    };
    /** ApiResponse[ProblemFiltersOutSchema] */
    ApiResponse_ProblemFiltersOutSchema_: {
      data?: components["schemas"]["ProblemFiltersOutSchema"] | null;
      /** Meta */
      meta?: {
        [key: string]: unknown;
      };
      /** Errors */
      errors?: components["schemas"]["ApiError"][];
    };
    /** ProblemFiltersOutSchema */
    ProblemFiltersOutSchema: {
      /** Sections */
      sections: components["schemas"]["SectionOutSchema"][];
      /** Topics */
      topics: components["schemas"]["TopicOutSchema"][];
      /** Tags */
      tags: components["schemas"]["TagOutSchema"][];
      /** Difficulties */
      difficulties: components["schemas"]["DifficultyOutSchema"][];
    };
    /** ApiResponse[ListResponse[ProblemListItemOutSchema]] */
    ApiResponse_ListResponse_ProblemListItemOutSchema__: {
      data?:
        | components["schemas"]["ListResponse_ProblemListItemOutSchema_"]
        | null;
      /** Meta */
      meta?: {
        [key: string]: unknown;
      };
      /** Errors */
      errors?: components["schemas"]["ApiError"][];
    };
    /** ListResponse[ProblemListItemOutSchema] */
    ListResponse_ProblemListItemOutSchema_: {
      /** Items */
      items: components["schemas"]["ProblemListItemOutSchema"][];
    };
    /** ProblemListItemOutSchema */
    ProblemListItemOutSchema: {
      /** Id */
      id: number;
      /** Title */
      title: string;
      /** Question */
      question: string;
      subject?: components["schemas"]["SubjectOutSchema"] | null;
      section: components["schemas"]["SectionOutSchema"];
      topic: components["schemas"]["TopicOutSchema"];
      difficulty: components["schemas"]["DifficultyOutSchema"];
      /** Tags */
      tags: components["schemas"]["TagOutSchema"][];
      /** Detail Url */
      detail_url: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  api_v1_auth_handlers_request_login_code_view: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AuthInputSchema"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_AuthOutSchema_"];
        };
      };
    };
  };
  api_v1_auth_handlers_confirm_view: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConfirmEmailInputSchema"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_AuthUserOutSchema_"];
        };
      };
    };
  };
  api_v1_auth_handlers_invite_confirm_view: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InviteTokenConfirmIn"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_AuthUserOutSchema_"];
        };
      };
    };
  };
  api_v1_auth_handlers_logout_view: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  api_v1_admin_handlers_invite_user_view: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserInputSchema"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_MessageSchema_"];
        };
      };
    };
  };
  api_v1_admin_handlers_get_users_list_view: {
    parameters: {
      query?: {
        created_from?: string | null;
        created_to?: string | null;
        search?: string | null;
        is_active?: boolean | null;
        offset?: number;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_ListPaginationResponse_UserOutSchema__"];
        };
      };
    };
  };
  api_v1_profile_handlers_get_user_view: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_UserOutSchema_"];
        };
      };
    };
  };
  api_v1_profile_handlers_update_user_view: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserUpdateSchema"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_UserOutSchema_"];
        };
      };
    };
  };
  api_v1_problems_handlers_profile_get_my_problems_list_view: {
    parameters: {
      query?: {
        created_from?: string | null;
        created_to?: string | null;
        search?: string | null;
        section_ids?: number[];
        topic_ids?: number[];
        tag_ids?: number[];
        difficulty?: components["schemas"]["Difficulty"] | null;
        status?: components["schemas"]["PublicationStatus"] | null;
        subject_slug?: string | null;
        offset?: number;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_ListPaginationResponse_ProblemOutSchema__"];
        };
      };
    };
  };
  api_v1_problems_handlers_profile_get_my_problem_detail_view: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        problem_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_ProblemOutSchema_"];
        };
      };
    };
  };
  api_v1_problems_handlers_profile_delete_my_problem_view: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        problem_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  api_v1_problems_handlers_profile_update_my_problem_view: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        subject_slug: string;
        problem_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProblemUpdateInSchema"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_ProblemMutationOutSchema_"];
        };
      };
    };
  };
  api_v1_problems_handlers_profile_create_problem_view: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        subject_slug: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProblemCreateInSchema"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_ProblemMutationOutSchema_"];
        };
      };
    };
  };
  api_v1_solutions_handlers_create_solution_view: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        problem_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SolutionCreateInSchema"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_SolutionMutationOutSchema_"];
        };
      };
    };
  };
  api_v1_solutions_handlers_update_solution_view: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        solution_id: number;
        problem_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SolutionUpdateInSchema"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_SolutionMutationOutSchema_"];
        };
      };
    };
  };
  api_v1_solutions_handlers_set_main_solution_view: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        problem_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetMainSolutionInSchema"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_SolutionMutationOutSchema_"];
        };
      };
    };
  };
  api_v1_subjects_handlers_get_subjects_view: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_list_SubjectOutSchema__"];
        };
      };
    };
  };
  api_v1_problems_handlers_subject_get_public_problems_list_view: {
    parameters: {
      query?: {
        created_from?: string | null;
        created_to?: string | null;
        search?: string | null;
        section_ids?: number[];
        topic_ids?: number[];
        tag_ids?: number[];
        difficulty?: components["schemas"]["Difficulty"] | null;
        offset?: number;
        limit?: number;
      };
      header?: never;
      path: {
        subject_slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_ListPaginationResponse_ProblemOutSchema__"];
        };
      };
    };
  };
  api_v1_problems_handlers_subject_get_problems_filters_view: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        subject_slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_ProblemFiltersOutSchema_"];
        };
      };
    };
  };
  api_v1_problems_handlers_public_get_recent_problems_list_view: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_ListResponse_ProblemListItemOutSchema__"];
        };
      };
    };
  };
  api_v1_problems_handlers_public_get_public_problem_detail_view: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        problem_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponse_ProblemOutSchema_"];
        };
      };
    };
  };
}
