# Generated by Django 5.2.8 on 2026-02-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, 'Пользователь'),
                    (2, 'Студент'),
                    (3, 'Преподаватель'),
                    (4, 'Администратор'),
                ],
                default=1,
                verbose_name='Роль',
            ),
        ),
    ]
