# Generated by Django 5.2.8 on 2025-11-29 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='basket',
            table='user_basket',
        ),
        migrations.AlterModelTable(
            name='basketdevice',
            table='user_basket_device',
        ),
    ]
