# Generated by Django 5.2.8 on 2026-02-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('USR', 'Пользователь'),
                    ('ADM', 'Администратор'),
                    ('TCH', 'Учитель'),
                    ('STU', 'Студент'),
                ],
                default='USR',
                verbose_name='Роль',
            ),
        ),
    ]
