# Generated by Django 6.0.2 on 2026-03-22 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorstudentmembership',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Ученик'),
        ),
        migrations.AddField(
            model_name='tutorstudentmembership',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Репетитор'),
        ),
        migrations.AddIndex(
            model_name='tutorstudentmembership',
            index=models.Index(fields=['student', 'is_active'], name='access_tuto_student_e0a39a_idx'),
        ),
        migrations.AddConstraint(
            model_name='tutorstudentmembership',
            constraint=models.UniqueConstraint(fields=('tutor', 'student'), name='uniq_tutor_student_pair'),
        ),
        migrations.AddConstraint(
            model_name='tutorstudentmembership',
            constraint=models.CheckConstraint(condition=models.Q(('tutor', models.F('student')), _negated=True), name='tutor_and_student_must_be_different'),
        ),
    ]
