# Generated by Django 6.0.4 on 2026-04-30 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tutorstudentmembership',
            new_name='tutor_stude_student_69e8a1_idx',
            old_name='access_tuto_student_e0a39a_idx',
        ),
        migrations.AlterModelTable(
            name='tutorstudentmembership',
            table='tutor_student_memberships',
        ),
    ]
