# Generated by Django 5.2.8 on 2026-01-17 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='ratings',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='devices.type'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'device')},
        ),
    ]
