# Generated by Django 5.2.8 on 2025-11-29 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='brand',
            table='device_brands',
        ),
        migrations.AlterModelTable(
            name='device',
            table='device',
        ),
        migrations.AlterModelTable(
            name='deviceinfo',
            table='device_info',
        ),
        migrations.AlterModelTable(
            name='rating',
            table='device_ratings',
        ),
        migrations.AlterModelTable(
            name='type',
            table='device_types',
        ),
    ]
