# Generated by Django 6.0.4 on 2026-05-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=150, verbose_name='Название задачи')),
                ('question', models.TextField(verbose_name='Дано')),
                ('difficulty', models.CharField(choices=[('easy', 'Лёгкая'), ('medium', 'Средняя'), ('hard', 'Сложная')], max_length=6, verbose_name='Сложность')),
                ('source', models.CharField(blank=True, default='', help_text='Например: ЕГЭ-2024, Сборник Рудзитиса, Олимпиада МГУ и т.п.', max_length=200, verbose_name='Источник')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='published', max_length=9, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
                'db_table': 'problems',
                'ordering': ('-created_at',),
                'default_related_name': 'problems',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=50, verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'раздел',
                'verbose_name_plural': 'Разделы',
                'db_table': 'sections',
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(default='Основное решение', max_length=50, verbose_name='Название решения')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основное решение')),
                ('is_published', models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть решение.', verbose_name='Опубликовано')),
                ('content', models.TextField(verbose_name='Решение')),
            ],
            options={
                'verbose_name': 'решение',
                'verbose_name_plural': 'Решения',
                'db_table': 'solutions',
                'ordering': ('-is_main', 'created_at'),
                'default_related_name': 'solutions',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Предмет')),
                ('slug', models.SlugField(help_text='Например: chemistry, math, physics', unique=True, verbose_name='Slug предмета')),
            ],
            options={
                'verbose_name': 'предмет',
                'verbose_name_plural': 'Предметы',
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Тэг')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'Теги',
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=50, verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'тема',
                'verbose_name_plural': 'Темы',
                'db_table': 'topics',
            },
        ),
    ]
