# Generated by Django 6.0.4 on 2026-04-30 15:50

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Предмет')),
                ('slug', models.SlugField(help_text='Например: chemistry, math, physics', unique=True, verbose_name='Slug предмета')),
            ],
            options={
                'verbose_name': 'предмет',
                'verbose_name_plural': 'Предметы',
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Тэг')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'Теги',
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=150, verbose_name='Название задачи')),
                ('question', models.TextField(verbose_name='Дано')),
                ('difficulty', models.CharField(choices=[('easy', 'Лёгкая'), ('medium', 'Средняя'), ('hard', 'Сложная')], max_length=6, verbose_name='Сложность')),
                ('source', models.CharField(blank=True, default='', help_text='Например: ЕГЭ-2024, Сборник Рудзитиса, Олимпиада МГУ и т.п.', max_length=200, verbose_name='Источник')),
                ('is_published', models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть задачу.', verbose_name='Опубликовано')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Если установить дату и время в будущем — можно делать отложенные публикации.', verbose_name='Дата и время публикации')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор задачи')),
                ('tags', models.ManyToManyField(blank=True, to='problems.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
                'db_table': 'problems',
                'ordering': ('-pub_date',),
                'default_related_name': 'problems',
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(default='Основное решение', max_length=50, verbose_name='Название решения')),
                ('content', models.TextField(verbose_name='Решение')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор решения')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'решение',
                'verbose_name_plural': 'Решения',
                'db_table': 'solutions',
                'ordering': ('created_at',),
                'default_related_name': 'solutions',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=50, verbose_name='Раздел')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='problems.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'раздел',
                'verbose_name_plural': 'Разделы',
                'db_table': 'sections',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=50, verbose_name='Тема')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='problems.section', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'тема',
                'verbose_name_plural': 'Темы',
                'db_table': 'topics',
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='problems.topic', verbose_name='Тема'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(models.F('subject'), django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name')), name='unique_section_per_subject'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(models.F('section'), django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name')), name='unique_topic_per_section'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['is_published', 'topic', '-pub_date'], name='problems_is_publ_f2b7bc_idx'),
        ),
    ]
