# Generated by Django 6.0.4 on 2026-05-23 18:35

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор задачи'),
        ),
        migrations.AddField(
            model_name='solution',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор решения'),
        ),
        migrations.AddField(
            model_name='solution',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem', verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='section',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='problems.subject', verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='problems.tag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='topic',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='problems.section', verbose_name='Раздел'),
        ),
        migrations.AddField(
            model_name='problem',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='problems.topic', verbose_name='Тема'),
        ),
        migrations.AddConstraint(
            model_name='solution',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('problem',), name='unique_main_solution_per_problem'),
        ),
        migrations.AddConstraint(
            model_name='solution',
            constraint=models.CheckConstraint(condition=models.Q(('is_main', True), ('is_published', False), _negated=True), name='main_solution_must_be_published'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(models.F('subject'), django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name')), name='unique_section_per_subject'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(models.F('section'), django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name')), name='unique_topic_per_section'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['status', 'topic', '-created_at'], name='problems_status_2ff041_idx'),
        ),
    ]
