# Generated by Django 6.0.4 on 2026-05-02 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Основное решение'),
        ),
        migrations.AddConstraint(
            model_name='solution',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('problem',), name='unique_main_solution_per_problem'),
        ),
    ]
