# Generated by Django 6.0.4 on 2026-05-02 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_solution_is_main_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solution',
            options={'default_related_name': 'solutions', 'ordering': ('-is_main', 'created_at'), 'verbose_name': 'решение', 'verbose_name_plural': 'Решения'},
        ),
    ]
