# Generated by Django 6.0.4 on 2026-05-08 14:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_alter_solution_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть решение.', verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='solution',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Если установить дату и время в будущем — можно делать отложенные публикации решений.', verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Если установить дату и время в будущем — можно делать отложенные публикации задач.', verbose_name='Дата и время публикации'),
        ),
    ]
