# Generated by Django 6.0.4 on 2026-05-09 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_solution_is_published_solution_pub_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'default_related_name': 'problems', 'ordering': ('-created_at',), 'verbose_name': 'задача', 'verbose_name_plural': 'задачи'},
        ),
        migrations.RemoveIndex(
            model_name='problem',
            name='problems_is_publ_f2b7bc_idx',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='pub_date',
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['is_published', 'topic', '-created_at'], name='problems_is_publ_481d9c_idx'),
        ),
        migrations.RemoveField(
            model_name='problem',
            name='pub_date',
        ),
    ]
