# Generated by Django 6.0.4 on 2026-05-21 17:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_alter_problem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='problem',
            name='problems_is_publ_481d9c_idx',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='is_published',
        ),
        migrations.AddField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='published', max_length=9, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='solution',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='published', max_length=9, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['status', 'topic', '-created_at'], name='problems_status_2ff041_idx'),
        ),
        migrations.RemoveField(
            model_name='problem',
            name='is_published',
        ),
    ]
