# Generated by Django 6.0.4 on 2026-05-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_remove_problem_problems_is_publ_481d9c_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='status',
        ),
        migrations.AddField(
            model_name='solution',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть решение.', verbose_name='Опубликовано'),
        ),
    ]
