# Generated by Django 6.0.4 on 2026-05-23 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_remove_solution_status_solution_is_published'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='solution',
            constraint=models.CheckConstraint(condition=models.Q(('is_main', True), ('is_published', False), _negated=True), name='main_solution_must_be_published'),
        ),
    ]
