name: Reusable Frontend CI

on:
  workflow_call:

jobs:
  frontend-checks:
    name: Frontend checks
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install dependencies
        run: |
          pwd
          ls -la
          ls -la frontend
          node -v
          npm -v
          grep -n "@emnapi/runtime" frontend/package-lock.json || true
          grep -n "@emnapi/core" frontend/package-lock.json || true
          make ci-install
          

      - name: Run frontend checks
        run: make ci-check
