name: Reusable Backend CI

on:
  workflow_call:
    secrets:
      SECRET_KEY:
        required: true

jobs:
  backend-checks:
    name: Backend checks
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: github_actions
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d github_actions"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        working-directory: backend

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: "True"
      DJANGO_ENV: "dev"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Debug env variables
        run: |
          echo "DEBUG=$DEBUG"
          echo "ENVIRONMENT=$ENVIRONMENT"

          if [ -z "$SECRET_KEY" ]; then
            echo "SECRET_KEY is empty"
            exit 1
          else
            echo "SECRET_KEY is present"
            echo "SECRET_KEY length: ${#SECRET_KEY}"
            echo "SECRET_KEY masked value: $SECRET_KEY"
          fi

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          save-cache: false
          cache-dependency-glob: backend/uv.lock

      - name: Install dependencies
        run: make ci-install

      - name: Run backend checks
        run: make ci-check