name: Reusable Frontend CI

on:
  workflow_call:

jobs:
  frontend-checks:
    name: Frontend checks
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: make ci-install

      - name: Run frontend checks
        run: make ci-check
